# Pre-generates authentic Swedish audio for SwedishCI using Microsoft's sv-SE neural voice (edge-tts)
# and copies existing human recordings from SwedishGames.
import asyncio
import hashlib
import json
import shutil
import sys
from pathlib import Path
import edge_tts

# Paths
SWEDISH_CI_DIR = Path(r"C:\Workspace\Workbench\SwedishCI")
SWEDISH_GAMES_DIR = Path(r"C:\Workspace\Workbench\SwedishGames")

CI_AUDIO = SWEDISH_CI_DIR / "audio"
CI_TTS = CI_AUDIO / "tts"

GAMES_AUDIO = SWEDISH_GAMES_DIR / "audio"
GAMES_TTS = GAMES_AUDIO / "tts"

VOICE = "sv-SE-SofieNeural"
CONCURRENCY = 5  # Allow up to 5 concurrent downloads to be fast

def fname(key):
    return hashlib.sha1(key.encode("utf-8")).hexdigest()[:12] + ".mp3"

async def synth(sem, text, dest, stats, index, total):
    async with sem:
        for attempt in range(4):
            try:
                await edge_tts.Communicate(text, VOICE, rate="-10%").save(str(dest))
                if dest.exists() and dest.stat().st_size > 400:
                    stats["ok"] += 1
                    print(f"[{index}/{total}] Generated TTS: '{text[:40]}...' -> {dest.name}")
                    return
                if dest.exists():
                    dest.unlink()
            except Exception as e:
                if dest.exists():
                    dest.unlink()
                print(f"Attempt {attempt+1} failed for '{text[:40]}...': {e}")
                await asyncio.sleep(2 * (attempt + 1))
        stats["err"] += 1
        print(f"\nFAILED: {text[:60]}")

async def main():
    CI_TTS.mkdir(parents=True, exist_ok=True)
    
    # 1. Copy human recordings from SwedishGames
    print("Copying human recordings (Sv-*.ogg) from SwedishGames...")
    human_copied = 0
    if GAMES_AUDIO.exists():
        for f in GAMES_AUDIO.glob("Sv-*.ogg"):
            dest_file = CI_AUDIO / f.name
            if not dest_file.exists():
                shutil.copy(f, dest_file)
            human_copied += 1
    print(f"Copied/verified {human_copied} human recordings.")

    # 2. Read speakable strings
    strings_file = SWEDISH_CI_DIR / "tools" / "speakable_strings.json"
    if not strings_file.exists():
        print("Error: speakable_strings.json not found! Run Node extractor first.")
        return
        
    texts = json.loads(strings_file.read_text(encoding="utf-8"))
    print(f"Loaded {len(texts)} speakable strings.")

    # 3. Check what needs generation, copy existing from SwedishGames if available
    todo = []
    copied_tts = 0
    for idx, t in enumerate(texts):
        key = t.lower()
        file_name = fname(key)
        dest = CI_TTS / file_name
        
        # If it already exists in SwedishCI, skip
        if dest.exists() and dest.stat().st_size > 400:
            continue
            
        # If it exists in SwedishGames, copy it
        games_source = GAMES_TTS / file_name
        if games_source.exists() and games_source.stat().st_size > 400:
            shutil.copy(games_source, dest)
            copied_tts += 1
            continue
            
        # Needs download
        todo.append((t, dest))

    print(f"Copied {copied_tts} existing TTS files from SwedishGames.")
    print(f"To generate: {len(todo)} clips.")

    # 4. Generate remaining TTS clips
    if todo:
        sem = asyncio.Semaphore(CONCURRENCY)
        stats = {"ok": 0, "err": 0}
        total = len(todo)
        
        # Run in chunks to prevent connection issues and show log progress intraday
        tasks = []
        for idx, (t, dest) in enumerate(todo):
            tasks.append(synth(sem, t, dest, stats, idx + 1, total))
            
        print("Starting voice synthesis via edge-tts...")
        # Run tasks
        await asyncio.gather(*tasks)
        print(f"\nSynthesis completed: {stats['ok']} succeeded, {stats['err']} failed.")

    # 5. Build and write audio-map.js
    print("Building audio-map.js...")
    amap = {}
    
    # Add all generated TTS files
    for t in texts:
        key = t.lower()
        file_name = fname(key)
        f = CI_TTS / file_name
        if f.exists() and f.stat().st_size > 400:
            amap[key] = "tts/" + f.name

    # Override with human recordings if they match the word
    human_count = 0
    for f in sorted(CI_AUDIO.glob("Sv-*.ogg")):
        word_key = f.stem[3:].lower()
        amap[word_key] = f.name
        human_count += 1

    # Write JS file
    js_content = (
        "// Generated by tools/generate_audio.py — Microsoft sv-SE-SofieNeural voice\n"
        "// + native-speaker recordings from Wikimedia Commons (Sv-*.ogg take priority).\n"
        f"const AUDIO_FILES = {json.dumps(amap, ensure_ascii=False)};\n"
    )
    (SWEDISH_CI_DIR / "audio-map.js").write_text(js_content, encoding="utf-8")
    
    total_size_mb = sum(f.stat().st_size for f in CI_TTS.glob("*.mp3")) / 1e6
    print(f"Completed! Mapped {len(amap)} phrases ({human_count} human recordings).")
    print(f"Total TTS size: {total_size_mb:.2f} MB saved to audio-map.js")

if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    asyncio.run(main())
